// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  content: string;
  icon: string;
  lang: string;
}
export const cssExports: CssExports;
export default cssExports;
